name: Docker Build/Publish Image 
on:  
  push:    
    branches: [ master ]  
jobs:   
  build:    
    runs-on: ubuntu-18.04    
    env:      
      DOCKER_REGISTRY: ghcr.io
      DOCKER_USERNAME: qtipeveryone
      DOCKER_IMAGE_NAME: arm_mhddos
      DOCKER_TARGET_PLATFORM: linux/arm64                 
    steps:    
    - name: Checkout the code       
      uses: actions/checkout@v1          
    - name: Set up Docker Buildx      
      uses: crazy-max/ghaction-docker-buildx@v1      
      with:        
        version: latest    
    - name: Prepare      
      if: success()      
      id: prepare      
      run: |        
        echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}
        echo ::set-output name=docker_image::${DOCKER_REGISTRY}/${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}
        echo ::set-output name=version::${GITHUB_RUN_NUMBER}
    - name: Docker Login
      if: success()
      run: |        
        echo "${{ github.token }}" | docker login ${DOCKER_REGISTRY} -u ${DOCKER_USERNAME} --password-stdin
    - name: Run Buildx (push image)
      if: success()
      run: |
        docker buildx build \
        --platform ${{ steps.prepare.outputs.docker_platform }} \
        --tag ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }} \
        --file ./Dockerfile \
        --output type=image,push=true .
    - name: Run Buildx (push image latest)
      if: success()
      run: |
        docker buildx build \
        --platform ${{ steps.prepare.outputs.docker_platform }} \
        --tag ${{ steps.prepare.outputs.docker_image }}:latest \
        --file ./Dockerfile \
        --output type=image,push=true .
